anyrun-org/anyrun

anyrun/src/main.rs
With this commit anyrun will appear above fullscreen windows
=> Set layer to overlay

anyrun/src/main.rs
Hi,
I've added a config var in order to be able to hide icons.
Regards
=> added config option to hide icons

README.md, anyrun/src/main.rs
Simple config var for hiding plugin info. also added the last 2 config options (icons and this) to the readme.
=> added a config option to hide the plugin info

README.md, anyrun/res/style.css, anyrun/src/main.rs
I've added "Fullscreen" as an Option for "Position". I couldn't figure out how to ignore other exclusive zones though, f.e. Waybar.
=> added option for fullscreen window

Cargo.lock, plugins/applications/src/lib.rs, plugins/applications/src/scrubber.rs, plugins/dictionary/Cargo.toml, plugins/dictionary/src/lib.rs, plugins/kidex/Cargo.toml, plugins/kidex/src/lib.rs, plugins/randr/src/lib.rs, plugins/symbols/src/lib.rs, plugins/translate/src/lib.rs
This PR makes plugins' max entries configurable.
=> Add max_entries config to plugins

.github/workflows/cachix.yml, README.md
Adds a public binary cache that users can use to pull pre-built binaries.
=> provide a binary cache for anyrun

.github/workflows/cachix.yml
@n3oney forgot to define a default package for the flake, which I didn't account for.
This fixes that.
=> provide a valid package for the buiild CI

.envrc, .github/workflows/cachix.yml, README.md, flake.lock, flake.nix, nix/default.nix, nix/hm-module.nix, nix/plugins/default.nix
Simplifies and cleans up the nix flake for further Nix development, also lays out groundwork for upcoming nixos or/and home-manager modules for anyrun.
=> nix: rewrite nix flake from ground up and introduce home-manager module

.github/workflows/cachix.yml, flake.nix
Fixes the CI failing due to a failing formatting check, also adds some module aliases to make module importing more intuitive.
=> Nix: fix binary cache CI and introduce module aliases

anyrun/src/main.rs
add default values for config options, so that no warning is given for missing fields
=> add defaults for missing config options

Cargo.lock, Cargo.toml, plugins/websearch/Cargo.toml, plugins/websearch/src/lib.rs
Hi,
i've created a basic websearch plugin that allows you to perform searches straight from anyrun.
What do you think?
Rergards
=> feat: websearch plugin

.github/workflows/cachix.yml, nix/default.nix, nix/plugins/default.nix
General cleanup in the nix derivations.
=> nix: cleanup

.github/workflows/cachix.yml, .github/workflows/check.yml, flake.lock
Bump flake inputs and hopefully get the binary cache to be working again.
Closes #94 (hopefully)
=> nix: housekeeping

anyrun-macros/src/lib.rs
=> [fix] Use ::core::option::Option and ::core::result::Result for the macros

README.md
fix flakes snippet (see #109 )
update home-manager snippet by replacing deprecated config options (see #117 )
=> Update README to fix code snippets

README.md
I made an error in my previous PR #138 and therefore didn't fix #109 as planned.
Sorry, this PR should right my wrongs.
=> fix: code snippet in README

flake.nix, nix/default.nix, nix/hm-module.nix
- **nix: inherit self from destructured args; get rid of rec**
- **nix: get rid of `with lib;` and inherit explicitly**
=> nix: additional cleanup

.github/workflows/cargo-audit.yml, .github/workflows/cargo-build.yml, .github/workflows/cargo-update.yml, .github/workflows/nix-build.yml, .github/workflows/nix-cache.yml
CI should take less time to trigger and build now.
=> ci: fine-grain trigger conditions

nix/default.nix
=> nix: add meta.mainProgram

plugins/applications/src/lib.rs
Previously, terminal applications which accepted arguments wouldn't be launched
because no arguments were provided. Thus, we strip the arguments to allow the
programs to launch.
=> plugins/applications: fix launching terminal apps with arguments

README.md
Mention the current status of the project in the README to avoid confusing users.
=> docs: include project status in the README

Cargo.lock, flake.lock, plugins/randr/Cargo.toml
Supersedes #154
(I could not figure out why co-authored-by doesn't work)
=> update hyprland-rs crate to 0.4.0-beta.1

nix/packages/anyrun.nix, nix/packages/plugin.nix
I'm blind *and* stupid. Cheers!
=> nix: fix incramental flags, again

README.md, nix/packages/anyrun.nix, nix/packages/plugin.nix
Also I'm not sure if [this](https://github.com/anyrun-org/anyrun/blob/d2017f224b2bfd7e33573c7070e7c3e2960c7dcc/anyrun/src/main.rs#L205) should also be changed?
=> chore: update links

anyrun/src/main.rs
=> full-screen window when close_on_click is set
