plugins/shell/src/lib.rs
Hi,
I've just removed the forced empty space in the prefix so you can configure f.e. "!" and just type "!shutdown now" instead of "! shutdown now" .... or even simply not have a prefix by configuring `prefix: ""`.
Regards
=> remove forced space character from prefix

anyrun-interface/src/lib.rs, anyrun/src/main.rs, plugins/applications/src/lib.rs, plugins/kidex/src/lib.rs, plugins/rink/src/lib.rs, plugins/shell/src/lib.rs, plugins/symbols/src/lib.rs, plugins/translate/src/lib.rs
This allows plugins to specify whether or not to interpret the `title` and `description` of each `Match` as pango markup.
Let me know if anything needs changing.
=> Add use_pango option for Match

anyrun/src/main.rs
Using the up arrow, down arrow, or tab key with no text input causes a panic.
=> Fix out of bounds panic

.envrc, README.md, default.nix, flake.lock, flake.nix
This PR adds a flake, to allow Nix(OS) users to install anyrun easily.
It doesn't have any configuration options or nix/home-manager modules.
The plugins are also built with the flake, kept in `lib/`, so to be able to use anyrun, you have to specify the full path to the plugin inside your configuration file. (like `"${pkgs.anyrun}/lib/libapplications.so"`
The above is documented.
The fact you have to use full paths will also allow plugins to be possibly packaged separately and used in the configs very easily.
Have confirmed with another person that it works for them!
=> feat: add nix flake

default.nix
not needed anymore as upstream started using an actual package of kidex-common
=> remove kidex-common hash on default.nix

README.md
forgot those were a thing, easy fix to invalid syntax for the cache URL
=> fix deprecated URL literal

plugins/applications/src/lib.rs, plugins/applications/src/scrubber.rs
Some desktop entries are required to be run under a certain directory; for instance, the desktop entries created by https://github.com/quickemu-project/quickemu.
I'm new to Rust, so any feedback is appreciated.
=> feat(applications): handle `Path` field in desktop entries

nix/hm-module.nix
Properly wraps the value of max_entries in the config.ron generated by home-manager with Some() when non-null, since that's what anyrun expects.
=> nix: fix non-null max_entries value in home-manager module

nix/hm-module.nix
bruh why tf is 0 not a valid float
=> fix: specify valid default value

nix/default.nix, nix/plugins/default.nix
Building the nix packages currently takes a long time as it compiles the dependencies of all the members of the cargo workspace.
Setting `buildAndTestSubdir` greatly speeds up the build.
=> nix: speed up nix build by only building sub directories

plugins/applications/src/lib.rs, plugins/applications/src/scrubber.rs
Hi,
so i've looked into the weighting of applications and i've done the following:
- fix bug where non-actions are weighted doubled
- prioritize actions over non-actions
- actions are also being weighted by the order in which they've been defined in the desktop file
So right now matching weight is like this: applications actual name > action name > keywords.
What do you think?
Regards
=> feat: changed applications matching/weighting

README.md, plugins/stdin/README.md
Hello,
I just notice that in some place the documentation was steal using `-o` to load a plugin even if isn't a valid parameter anymore, so I replaced it with `--plugins`.
=> Replace `-o` with `--plugins` in documentation

plugins/applications/src/lib.rs
The desktop entries edited by applications like kmenuedit will leave blank in the path, and that causes the `current_dir` of the command to become `""`, making `os error 2 (no such file or directory)`.
Now it would try to run in env::current_dir if the path was not set or not proper
=> fix: Desktop Entries without proper path wouldn't run

README.md
Though mostly undocumented, setting `nix.settings.substituters` overwrites any previous entries, including the default nixpkgs binary cache. Using `nix.settings.extra-substituters` appends to the list instead, independent of any nixpkgs or NixOS module logic.
See the [nix manual entry](https://nixos.org/manual/nix/stable/command-ref/conf-file.html?highlight=extra-substituters#file-format)
=> Use `nix.settings.extra-*`

flake.nix
Uses flake-parts' internal easyOverlay module to generate an overlay of packages for those prefer overlays for some reason. I'd add a warning to the code, but it's a valid use case regardless of how bad of an idea overlays are.
Supersedes #159
=> nix: generate overlay from exposed packages

README.md, flake.nix
=> nix: use the correct self attribute in the module import

flake.lock, flake.nix
Use `nix develop` with a clean environment to build Anyrun.
=> CI: fix build workflow

plugins/applications/src/lib.rs
This reverts commit 08f3d0bfcb1dfcad66d23a77bf6445f2ec7bd818.
Functionality was already present in scrubber.rs
=> Revert "plugins/applications: fix terminal apps with arguments"

anyrun/src/main.rs
This adds selection/action support for the numpad enter key.
This is because previously only the return key worked but that one is broken on my keyboard.
So I added the numpad key as well because why not. ¯\\\_(ツ)_/¯
=> Support KP_Enter as selection key

plugins/applications/README.md, plugins/applications/src/lib.rs
This option lets you add a script that can transform the command of a desktop option (in my case to prepend `uwsm app --`), or otherwise cause side effects like collecting statistics or running notify-send.
=> plugins/applications: add preprocess_exec_script option

plugins/applications/src/lib.rs
Currently, the order of entries is partially random when multiple entries have the same score.
This is an issue when trying to open applications such as LibreOffice, which comes with multiple desktop entries (LibreOffice, LibreOffice Writer, LibreOffice Draw, LibreOffice Impress...). The "LibreOffice" entry may be completely inaccessible when just typing "LibreOffice" since the list is by default truncated to 5 entries and the entry may be preceded by more than 5 other entries.
The change in this commit sorts the entries alphabetically when they have the same score, ensuring that shorter entries are always listed first. Therefore, when typing "LibreOffice," the list always begins with "LibreOffice," "LibreOffice Base," "LibreOffice Calc"...
=> plugins/applications: Sort entries alphabetically to ensure deterministic ordering

plugins/websearch/src/lib.rs
fix websearch not searching properly due to missing double quotes
=> Fix Websearch

flake.nix
Small change, I noticed that this plugin was added and I couldn't use it in my flake. Really cool plugin by the way!
=> flake: enable the nix-run plugin

README.md, nix/modules/home-manager.nix
Just keeping the module up to date. Added an `extraLines` option that gets inserted into the `Config` object so that users can take advantage of config changes without waiting for the module to be updated.
I also took the liberty of mentioning how to disable HM's module to use our own.
=> nix/hm: add keybinds and extraLines options

Cargo.lock, plugins/rink/Cargo.toml, plugins/rink/src/lib.rs
I wanted to be able to use = as a prefix for the rink plugin, so I implemented the prefix config option for it. I mostly copied the structure from the nix-run. Let me know if any changes should be made!
=> plugins/rink: Add prefix config option
